name: 'Go Test'
description: 'Run Go tests with race detection and shuffle'
author: 'sivchari'

inputs:
  go-version-file:
    description: 'Path to go.mod file for Go version detection'
    required: false
    default: 'go.mod'
  working-directory:
    description: 'Working directory to run tests in'
    required: false
    default: '.'
  test-args:
    description: 'Additional arguments to pass to go test'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@f6164bd40689b23db8b25a93313d00c20e5f9173 # v5
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache: true
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        go test ./... -shuffle=on -v -race ${{ inputs.test-args }}

branding:
  icon: 'check-circle'
  color: 'green'